services:
  build_image:
    image: carla-ros-bridge
    build: 
      context: ./..
      dockerfile: docker/Dockerfile
      args:
        - ROS_DISTRO=foxy
        - CARLA_VERSION=0.9.13

  colcon_build:
    image: carla-ros-bridge
    tty: true
    working_dir: /opt/carla-ros-bridge/src 
    volumes:
      - ../:/opt/carla-ros-bridge/src:rw
    command: colcon build --symlink-install

  run_bridge:
    image: carla-ros-bridge
    tty: true
    ipc: host
    network_mode: host
    user: root
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
    environment:
      - DISPLAY=${DISPLAY}  # Forward display to the host
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp 
      - FASTRTPS_DEFAULT_PROFILES_FILE=/dds.xml 
      - ROS_DOMAIN_ID=31 
    volumes:
      -  /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ../:/opt/carla-ros-bridge/src:rw
      - /dev/shm:/dev/shm
      - ../docker/content/dds.xml:/dds.xml
    working_dir: /opt/carla-ros-bridge 
    command: ros2 launch carla_ros_bridge carla_ros_bridge_with_example_ego_vehicle.launch.py

  generate_traffic:
    image: carla-ros-bridge
    tty: true
    ipc: host
    network_mode: host
    user: root
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
    environment:
      - DISPLAY=${DISPLAY}  # Forward display to the host
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp 
      - FASTRTPS_DEFAULT_PROFILES_FILE=/dds.xml 
      - ROS_DOMAIN_ID=31 
    volumes:
      -  /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ../:/opt/carla-ros-bridge/src:rw
      - /dev/shm:/dev/shm
      - ../docker/content/dds.xml:/dds.xml
    working_dir: /opt/carla-ros-bridge 
    command: python3 /opt/carla/PythonAPI/examples/generate_traffic.py





